### ISSUE TITLE
Create Containers: Providing an XLSX document gives an error

### ISSUE THREAD

**Issue by dbujold** [c3g/fms#23]
Error message obtained: "InvalidDimensions encountered while trying to read file: Container Creation v0.2 example.xlsx"
Template used: "Container Creation v0.2"

CSV documents work fine.

If it's more complex to support XLSX documents, I suggest only supporting CSV.

**Comment by davidlougheed** [comment]
Fixed in 5c4d9a7a51058e5eac67fdbcecf83dcb3950efcf
