### ISSUE TITLE
Add sample (using web interface): Creating a sample gives "Server Error (500)"

### ISSUE THREAD

**Issue by dbujold** [c3g/fms#24]
Steps to reproduce:
Choose Biospecimen "Blood", enter a value for field "Name", and submit page.

**Comment by dbujold** [comment]
If I provide other fields that I didn't fill previously, it works, though.

**Comment by davidlougheed** [comment]
i've fixed in e41d392011e9529002e372e9cf34625df4b3e1df (not deployed yet though)
