### ISSUE TITLE
When creating an extraction, the confirmation screen doesn't replicate the columns content as I provided them.

### ISSUE THREAD

**Issue by dbujold** [c3g/fms#28]
For instance, in this screenshot, I provided a "Nucleic acid location barcode".

![Selection_112](https://user-images.githubusercontent.com/9681379/79092812-14d2b480-7d20-11ea-80d6-09d593ba3844.png)

**Comment by dbujold** [comment]
Looking good, but the only thing missing in the confirmation screen is the "Nucleic Acid Location Coord".

**Comment by dbujold** [comment]
![Selection_115](https://user-images.githubusercontent.com/9681379/81133946-2c691b80-8f21-11ea-86b4-a349274870b6.png)

**Comment by dbujold** [comment]
The column now appear, thanks.

However, I'm now getting a new validation error on invalid Experiment Group, which is not a value in this template.

**Comment by davidlougheed** [comment]
That issue will not occur with a fresh database.
