### ISSUE TITLE
Importing Sample submission file

### ISSUE THREAD

**Issue by cdarmond** [c3g/fms#52]
Using Sample submission sheet to import 96 samples in 2D barcoded racks (Tubes in rack)
Error message for all 96 lines:
Container matching Query does not exist

**Comment by davidlougheed** [comment]
@cdarmond if possible can you send me the spreadsheet you were using to test this?

**Comment by cdarmond** [comment]
Thank-you!


Corinne Darmond, MSc., Research Assistant.
Genome Sciences Lab, Dr Ioannis Ragoussis | McGill Genome Centre
740 Dr. Penfield Ave room 2304| Montreal (Quebec) H3A 0G1 |
T: 514.398.3890  cdarmond@mcgill.ca
[Logo McGill]

________________________________

**Comment by dbujold** [comment]
@davidlougheed Was this solved in the end?

**Comment by cdarmond** [comment]
Yes thank you. Alexander's demo did  the trick!

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
