### ISSUE TITLE
Keep a copy of all submitted XLSX/CSV templates

### ISSUE THREAD

**Issue by dbujold** [c3g/fms#62]

**Comment by dbujold** [comment]
So right now the templates are kept but there's no way to obtain them, correct?

**Comment by zxenia** [comment]
The imported xlsx files are stored in the dedicated folder on the server. The following metadata about each of them is stored in the database: when the file was imported, by whom (username), path to the location on the server, and the filename (filename also contains a timestamp and the username). They can be obtained directly from the server.

**Comment by dbujold** [comment]
OK, I'll create an issue for the future to have a way to extract them from the interface.

**Comment by davidlougheed** [comment]
Since this is fixed, I'll close it (the new issue can be used to track the UI stuff)
