### ISSUE TITLE
Home > Sample Tracking > Individuals (No Template)

### ISSUE THREAD

**Issue by ttir** [c3g/fms#69]
No Download Template   button
--

**Comment by zxenia** [comment]
We were not provided with such a template.

**Comment by ttir** [comment]
Ok. Mislead by the import button

**Comment by zxenia** [comment]
@ttir it's a good point! I'll leave the issue open.

**Comment by dbujold** [comment]
If there is no template, maybe we should remove the "Import" button as well?

**Comment by zxenia** [comment]
We can do that, yes.

**Comment by dbujold** [comment]
All good, closing.
