### ISSUE TITLE
Is the "sample update" comment for the update, or the sample?

### ISSUE THREAD

**Issue by davidlougheed** [c3g/fms#71]
Right now, setting a sample update comment will change the comment of the original sample. However, to me, it's unclear if this comment is about the *update* or is updating the comment about the *sample*.

**Comment by dbujold** [comment]
Alex confirmed that this is a comment about the update.

**Comment by dbujold** [comment]
Implemented by @davidlougheed as an additional "Update Comment" field, that's separate from the "Comment" field.
